package com.orderflow.orderservice.entity;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * ORDER LINE ITEM ENTITY CLASS
 * - Represents a single "line item" inside of an order.
 * - Stores the quantity and base unit price incents to avoid floating point issues.
 * - Belongs to exactly one order.
 * - AccessLevel.PROTECTED on no-args constructor to prevent direct instantiation without using the builder or factory methods.
 * - EqualsAnndHashCode(onlyExplicitlyIncluded = true) to avoid equals/hashCode on all fields.
 * - ToString(exclude = "order") to avoid recursive toString() calls.
 * 
 * @author Emmanuel Taylor
 */
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString(exclude = "order")
@Entity
@Table(
    name = "order_line_items",
    uniqueConstraints = {
        /** Ensures UID is unique within the same order. */
        @UniqueConstraint(name = "uk_order_line_items_order_uid", columnNames = { "order_id", "uid" }),
        
        /** Ensures line numbers are unique within the same order. */
        @UniqueConstraint(name = "uk_order_line_items_order_line_number", columnNames = { "order_id", "line_number" })
    }
)
public class OrderLineItem {
    
    /** Primary key. UUID works will in distributed/event-driven systems as well as
     *  Kafka/Event IDs. Generated by Hibernate using the UUID strategy. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    @EqualsAndHashCode.Include
    private UUID id;

    /** A stable identifier used in API responses. */
    @Column(name = "uid", nullable = false)
    private String uid;

    /** Explicit ordering within the order (1..N). This is used instead of relying on
     *  UUID sorting so responses always come back in a predictable order. */
    @Column(name = "line_number", nullable = false)
    private int lineNumber;

    /** Display name of the item. */
    @Column(name = "name", nullable = false)
    private String name;

    /** Quantity purchased. In the API request we use a String, but in persistence
     *  we store it as an int for simplicity. */
    @Column(name = "quantity", nullable = false)
    private int quantity;

    /** Unit price in cents (smallest denomination). */
    @Column(name = "base_price_amount", nullable = false)
    private long basePriceAmount;

    /**
     * Many LineItems belong to one Order (N:1 relationship).
     * FetchType.LAZY avoids loading all orders unless explicitly needed.
     * Updatable=false to prevent moving a line item from one Order to another.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false, updatable = false)
    private Order order;
}
